### ISSUE TITLE
installation with pip3 fails: `ImportError: No module named 'IPython.kernel.kernelspec'`

### ISSUE THREAD

**Issue by NHDaly** [takluyver/bash_kernel#28]
Hi, I'm having trouble installing `bash_kernel`.

I have downloaded `ipython3` via `sudo apt-get install ipython3 && sudo apt-get install ipython3-notebook` and `pip3` via `sudo apt-get install python3-pip`. Everything worked.

Now, when I run `sudo pip3 install bash_kernel`, I see:

```
Downloading/unpacking bash-kernel
  Downloading bash_kernel-0.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/bash-kernel/setup.py) egg_info for package bash-kernel

Downloading/unpacking pexpect>=3.3 (from bash-kernel)
  Downloading pexpect-3.3.tar.gz (132kB): 132kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pexpect/setup.py) egg_info for package pexpect

Installing collected packages: bash-kernel, pexpect
  Running setup.py install for bash-kernel

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/bash-kernel/setup.py", line 53, in <module>
        'Topic :: System :: Shells',
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip_build_root/bash-kernel/setup.py", line 20, in run
        from IPython.kernel.kernelspec import install_kernel_spec
    ImportError: No module named 'IPython.kernel.kernelspec'
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/bash-kernel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bki_y0w5-record/install-
record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/bash_kernel

copying bash_kernel/images.py -> build/lib/bash_kernel

copying bash_kernel/__init__.py -> build/lib/bash_kernel

copying bash_kernel/__main__.py -> build/lib/bash_kernel

copying bash_kernel/kernel.py -> build/lib/bash_kernel

running install_lib

creating /usr/local/lib/python3.4

creating /usr/local/lib/python3.4/dist-packages

creating /usr/local/lib/python3.4/dist-packages/bash_kernel

copying build/lib/bash_kernel/images.py -> /usr/local/lib/python3.4/dist-packages/bash_kernel

copying build/lib/bash_kernel/__init__.py -> /usr/local/lib/python3.4/dist-packages/bash_kernel

copying build/lib/bash_kernel/__main__.py -> /usr/local/lib/python3.4/dist-packages/bash_kernel

copying build/lib/bash_kernel/kernel.py -> /usr/local/lib/python3.4/dist-packages/bash_kernel

byte-compiling /usr/local/lib/python3.4/dist-packages/bash_kernel/images.py to images.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/bash_kernel/__init__.py to __init__.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/bash_kernel/__main__.py to __main__.cpython-34.pyc

byte-compiling /usr/local/lib/python3.4/dist-packages/bash_kernel/kernel.py to kernel.cpython-34.pyc

running install_egg_info

running egg_info

creating bash_kernel.egg-info

writing dependency_links to bash_kernel.egg-info/dependency_links.txt

writing bash_kernel.egg-info/PKG-INFO

writing requirements to bash_kernel.egg-info/requires.txt

writing top-level names to bash_kernel.egg-info/top_level.txt

writing manifest file 'bash_kernel.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



reading manifest file 'bash_kernel.egg-info/SOURCES.txt'

writing manifest file 'bash_kernel.egg-info/SOURCES.txt'

Copying bash_kernel.egg-info to /usr/local/lib/python3.4/dist-packages/bash_kernel-0.3.egg-info

writing list of installed files to '/tmp/pip-bki_y0w5-record/install-record.txt'

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/bash-kernel/setup.py", line 53, in <module>

    'Topic :: System :: Shells',

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/tmp/pip_build_root/bash-kernel/setup.py", line 20, in run

    from IPython.kernel.kernelspec import install_kernel_spec

ImportError: No module named 'IPython.kernel.kernelspec'

----------------------------------------
Cleaning up...
```

Thanks for your help! I'm excited to try this! (And thanks @jeroenjanssens for the [very cool article](http://jeroenjanssens.com/2015/02/19/ibash-notebook.html); it brought me here!)

**Comment by takluyver** [comment]
You need IPython >= 3.x for that to work, while apt still only has 2.3. You'll need to `pip3 install --upgrade ipython[notebook]`.

**Comment by NHDaly** [comment]
perfect. Thanks!

(`pip3 install --upgrade ipython` worked for me. There was no `ipythonnotebook` or `ipython-notebook` package in pip, but it seems to have worked without that being necessary!)

**Comment by takluyver** [comment]
Great. :-)

I was actually suggesting the syntax `ipython[notebook]` - literally with the square brackets. That ensures that the optional dependencies for the notebook are installed. But if it works anyway, you don't need to worry about that.

**Comment by NHDaly** [comment]
Oh haha, perfect. Yeah, I tried that syntax exactly first, but it didn't
work either, and then I felt dumb because I was like "oh obviously that's
not what he meant." :p
