### ISSUE TITLE
Kernel did not respond: pexpect.exceptions.TIMEOUT

### ISSUE THREAD

**Issue by fzinfz** [takluyver/bash_kernel#53]
Dead kernel in jupyter.
Python 3.5.2 | Anaconda 4.1.1 (64-bit) | pexpect 4.0.1

jupyter-console gives pexpect.exceptions.TIMEOUT error. 
Any advice would be appreciated.

```
root@LA1:~# jupyter-console   --kernel='Bash'  --debug
[ZMQTerminalIPythonApp] Searching ['/root', '/root/.jupyter', '/root/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root
[ZMQTerminalIPythonApp] Connection File not found: /root/.local/share/jupyter/runtime/kernel-21653.json
[ZMQTerminalIPythonApp] Found kernel bash in /usr/local/share/jupyter/kernels
[ZMQTerminalIPythonApp] Native kernel (python3) available from /root/anaconda3/lib/python3.5/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: ['/root/anaconda3/envs/py35/bin/python', '-m', 'bash_kernel', '-f', '/root/.local/share/jupyter/runtime/kernel-21653.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:59447
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:47610
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:47610
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:35024
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:35024
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:40135
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:40135
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:42427
Jupyter Console 4.1.1

[ZMQTerminalIPythonApp] Starting the jupyter console mainloop...
Traceback (most recent call last):
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 97, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/pty_spawn.py", line 452, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/py35/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/kernel.py", line 46, in __init__
    self._start_bash()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/kernel.py", line 55, in _start_bash
    self.bashwrapper = replwrap.bash()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 113, in bash
    extra_init_cmd="export PAGER=cat")
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f30cee93a58>
command: /bin/bash
args: ['/bin/bash', '--rcfile', '/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/bashrc.sh']
searcher: None
buffer (last 100 chars): 'root@LA1:~# '
before (last 100 chars): 'root@LA1:~# '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 21668
child_fd: 45
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
ERROR: Kernel did not respond

Shutting down kernel

```

Here is the working default python kernel:
```
root@LA1:~# jupyter-console   --debug
[ZMQTerminalIPythonApp] Searching ['/root', '/root/.jupyter', '/root/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root
[ZMQTerminalIPythonApp] Connection File not found: /root/.local/share/jupyter/runtime/kernel-21723.json
[ZMQTerminalIPythonApp] Found kernel bash in /usr/local/share/jupyter/kernels
[ZMQTerminalIPythonApp] Native kernel (python3) available from /root/anaconda3/lib/python3.5/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: ['/root/anaconda3/bin/python', '-m', 'ipykernel', '-f', '/root/.local/share/jupyter/runtime/kernel-21723.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:35255
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:51449
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:51449
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:53805
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:53805
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:60247
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:60247
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:52567
Jupyter Console 4.1.1

[ZMQTerminalIPythonApp] Starting the jupyter console mainloop...

In [1]: import sys

In [2]: sys.version
Out[2]: '3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

In [3]: import pexpect

In [4]: pexpect.__version__
Out[4]: '4.0.1'
```

**Comment by takluyver** [comment]
Can you try upgrading pexpect to the latest version, 4.2.0?

It looks like it's not in Anaconda, so you may need to `conda uninstall pexpect` and `pip install pexpect`.

**Comment by fzinfz** [comment]
Since `conda uninstall pexpect` also removed notebook and jupyter_console, I reinstalled pexpect via conda(also upgraded jupyter_console to 5.0.0) and did a `pip install pexpect --upgrade` to upgrade pexpect to 4.2.0.  Then besides `pexpect.exceptions.TIMEOUT` error, I also got `queue.Empty` error from jupyter_client and `RuntimeError` error from jupyter_console.

It looks like pexpect bug or some compatibility issues on my Debian system. I will try on another clean machine. Thanks.

```
root@LA1:/tmp# pip install pexpect --upgrade
Collecting pexpect
  Using cached pexpect-4.2.0-py2.py3-none-any.whl
Requirement already up-to-date: ptyprocess>=0.5 in /root/anaconda3/lib/python3.5/site-packages (from pexpect)
Installing collected packages: pexpect
  Found existing installation: pexpect 4.0.1
    DEPRECATION: Uninstalling a distutils installed project (pexpect) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a di
stutils project will only partially uninstall the project.
    Uninstalling pexpect-4.0.1:
      Successfully uninstalled pexpect-4.0.1
Successfully installed pexpect-4.2.0
root@LA1:/tmp# jupyter-console
Jupyter console 5.0.0

Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.



In [1]: import pexpect

In [2]: pexpect.__version__
Out[2]: '4.2.0'

In [3]:
Do you really want to exit ([y]/n)? y
Shutting down kernel
root@LA1:/tmp# jupyter-console  --kernel='Bash'  --debug
[ZMQTerminalIPythonApp] Searching ['/tmp', '/root/.jupyter', '/root/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /tmp
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/anaconda3/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /tmp
[ZMQTerminalIPythonApp] Connection File not found: /root/.local/share/jupyter/runtime/kernel-22761.json
[ZMQTerminalIPythonApp] Found kernel bash in /usr/local/share/jupyter/kernels
[ZMQTerminalIPythonApp] Native kernel (python3) available from /root/anaconda3/lib/python3.5/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: ['/root/anaconda3/envs/py35/bin/python', '-m', 'bash_kernel', '-f', '/root/.local/share/jupyter/runtime/kernel-22761.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:34519
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:42133
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:42133
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:35056
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:35056
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:36831
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:36831
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:53904
Traceback (most recent call last):
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/py35/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/kernel.py", line 46, in __init__
    self._start_bash()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/bash_kernel/kernel.py", line 55, in _start_bash
    self.bashwrapper = replwrap.bash()
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 113, in bash
    extra_init_cmd="export PAGER=cat")
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f432cf8ab38>
command: /bin/bash
args: [b'/bin/bash', b'--rcfile', b'/root/anaconda3/envs/py35/lib/python3.5/site-packages/pexpect/bashrc.sh']
buffer (last 100 chars): 'root@LA1:/tmp# '
before (last 100 chars): 'root@LA1:/tmp# '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 22776
child_fd: 45
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("\$")
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 302, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/root/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_console/app.py", line 110, in init_shell
    client=self.kernel_client,
  File "/root/anaconda3/lib/python3.5/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 251, in __init__
    self.init_kernel_info()
  File "/root/anaconda3/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 305, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request

root@LA1:/tmp# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

The console output below shows `conda uninstall pexpect` would also uninstall many key components:

```
root@LA1:~/Dropbox/bash# conda uninstall pexpect
Fetching package metadata .......
Solving package specifications: ..........

Package plan for package removal in environment /root/anaconda3:

The following packages will be REMOVED:

    _nb_ext_conf:     0.2.0-py35_0
    anaconda:         4.1.1-np111py35_0
    ipykernel:        4.3.1-py35_0
    ipython:          4.2.0-py35_0
    ipywidgets:       4.1.1-py35_0
    jupyter:          1.0.0-py35_3
    jupyter_console:  4.1.1-py35_0
    nb_anacondacloud: 1.1.0-py35_0
    nb_conda:         1.1.0-py35_0
    nb_conda_kernels: 1.0.3-py35_0
    nbpresent:        3.0.2-py35_0
    notebook:         4.2.1-py35_0
    pexpect:          4.0.1-py35_0
    qtconsole:        4.2.1-py35_0
    spyder:           2.3.9-py35_0

Proceed ([y]/n)? 
```

**Comment by takluyver** [comment]
I think you've upgraded pexpect in a different environment from where your bash kernel is installed. Try:

```
source activate py35
pip install --upgrade pexpect
```

**Comment by fzinfz** [comment]
Oh, `activate py35` solved the problem, both jupyter-console and notebook worked! thanks!

```
root@LA1:/tmp# source activate py35
(py35) root@LA1:/tmp# pip install --upgrade pexpect
Collecting pexpect
  Using cached pexpect-4.2.0-py2.py3-none-any.whl
Requirement already up-to-date: ptyprocess>=0.5 in /root/anaconda3/envs/py35/lib/python3.5/site-packages (from pexpect)
Installing collected packages: pexpect
  Found existing installation: pexpect 4.0.1
    DEPRECATION: Uninstalling a distutils installed project (pexpect) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a di
stutils project will only partially uninstall the project.
    Uninstalling pexpect-4.0.1:
      Successfully uninstalled pexpect-4.0.1
Successfully installed pexpect-4.2.0
(py35) root@LA1:/tmp# jupyter-console  --kernel='Bash'  --debug
[ZMQTerminalIPythonApp] Searching ['/tmp', '/root/.jupyter', '/root/anaconda3/envs/py35/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/anaconda3/envs/py35/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /tmp
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/anaconda3/envs/py35/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /root/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /tmp
[ZMQTerminalIPythonApp] Connection File not found: /root/.local/share/jupyter/runtime/kernel-23116.json
[ZMQTerminalIPythonApp] Found kernel bash in /usr/local/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel metakernel_bash in /usr/local/share/jupyter/kernels
[ZMQTerminalIPythonApp] Native kernel (python3) available from /root/anaconda3/envs/py35/lib/python3.5/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: ['/root/anaconda3/envs/py35/bin/python', '-m', 'bash_kernel', '-f', '/root/.local/share/jupyter/runtime/kernel-23116.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:55829
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:54245
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:54245
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:45494
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:45494
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:40445
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:40445
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:49176
Jupyter Console 4.1.1

[ZMQTerminalIPythonApp] Starting the jupyter console mainloop...

In [1]:
```

**Comment by takluyver** [comment]
Great, thanks. For the record, I'm guessing that you have customised your bash prompt - the newer version of Pexpect contains a fix to work around that.

**Comment by nvgoldin** [comment]
Hi,
I'm getting the same error in venv:

```
>pip freeze
bash-kernel==0.5
bleach==1.5.0
decorator==4.0.10
entrypoints==0.2.2
html5lib==0.9999999
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
MarkupSafe==0.23
mistune==0.7.3
nbconvert==5.0.0
nbformat==4.2.0
notebook==4.3.0
pandocfilters==1.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
Pygments==2.1.3
pyzmq==16.0.2
qtconsole==4.2.1
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
testpath==0.3
tornado==4.4.2
traitlets==4.3.1
wcwidth==0.1.7
widgetsnbextension==1.2.6
```


```python
> ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
[I 23:41:11.472 NotebookApp] Serving notebooks from local directory: /home/ngoldin/src/gerrit.ovirt.org
[I 23:41:11.472 NotebookApp] 0 active kernels 
[I 23:41:11.472 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=921acd8bb5d7fe88afea24131068a01195ffb857c21bd191
[I 23:41:11.472 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:41:15.248 NotebookApp] Creating new notebook in 
[W 23:41:15.979 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161218234111 (::1) 9.73ms referer=http://localhost:8888/notebooks/Untitled3.ipynb?kernel_name=bash
[I 23:41:16.019 NotebookApp] Kernel started: 0e4351c7-7e1e-42a5-9a58-d000e0339217
[W 23:41:26.183 NotebookApp] Timeout waiting for kernel_info reply from 0e4351c7-7e1e-42a5-9a58-d000e0339217
Traceback (most recent call last):
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/bash_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/ipykernel/kernelapp.py", line 454, in initialize
    self.init_kernel()
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/ipykernel/kernelapp.py", line 365, in init_kernel
    user_ns=self.user_ns,
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/bash_kernel/kernel.py", line 84, in __init__
    self._start_bash()
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/bash_kernel/kernel.py", line 107, in _start_bash
    line_output_callback=self.process_output)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/bash_kernel/kernel.py", line 36, in __init__
    prompt_change, extra_init_cmd=extra_init_cmd)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f62f2571208>
command: /usr/bin/bash
args: [b'/usr/bin/bash', b'--rcfile', b'/home/ngoldin/virtualenv/ipython-bash/lib64/python3.5/site-packages/pexpect/bashrc.sh']
buffer (last 100 chars): '40msrc\xa0\x1b[0;38;5;245;48;5;240;22m\ue0b1\xa0\x1b[0;38;5;252;48;5;240;1mgerrit.ovirt.org\xa0\x1b[0;38;5;240;49;22m\ue0b0\xa0\x1b[0m'
before (last 100 chars): '40msrc\xa0\x1b[0;38;5;245;48;5;240;22m\ue0b1\xa0\x1b[0;38;5;252;48;5;240;1mgerrit.ovirt.org\xa0\x1b[0;38;5;240;49;22m\ue0b0\xa0\x1b[0m'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 22860
child_fd: 46
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("\$")
^C[I 23:41:48.672 NotebookApp] interrupted
Serving notebooks from local directory: /home/ngoldin/src/gerrit.ovirt.org
1 active kernels 
The Jupyter Notebook is running at: http://localhost:8888/?token=921acd8bb5d7fe88afea24131068a01195ffb857c21bd191
Shutdown this notebook server (y/[n])? [I 23:41:49.020 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 0e4351c7-7e1e-42a5-9a58-d000e0339217 restarted
No answer for 5s: resuming operation...

```


any ideas?
