### ISSUE TITLE
pexpect Unicode issue prevents kernel startup

### ISSUE THREAD

**Issue by thomasjm** [takluyver/bash_kernel#57]
I'm unable to start a Bash kernel with the latest version--as soon as I enter code in Jupyter, I get an exception like this:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/bash_kernel/kernel.py", line 147, in do_execute
    self.bashwrapper.run_command(str(code.rstrip()), timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/replwrap.py", line 95, in run_command
    if self._expect_prompt(timeout=timeout) == 1:
  File "/usr/local/lib/python2.7/dist-packages/bash_kernel/kernel.py", line 44, in _expect_prompt
    timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 383, in expect_exact
    pattern_list = [prepare_pattern(p) for p in pattern_list]
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 377, in prepare_pattern
    self._pattern_type_err(pattern)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 172, in _pattern_type_err
    for ast in self.allowed_string_types])
TypeError: got <type 'str'> ('\r\n') as pattern, must be one of: <type 'unicode'>, pexpect.EOF, pexpect.TIMEOUT
```

It seems there's some kind of string issue going on with `pexpect`

**Comment by takluyver** [comment]
Fixed by #58

**Comment by thomasjm** [comment]
Thanks! @takluyver , any chance you could release the latest version to pip so that this works again?

**Comment by takluyver** [comment]
Released
