### ISSUE TITLE
Kernel crashes when Jupyter Notebook is started from JupyterHub

### ISSUE THREAD

**Issue by riccardomurri** [takluyver/bash_kernel#59]
Whn trying to use the BASH kernel from a Jupyter Notebook started from
JupyterHub, I get the following traceback::

    [I 2017-02-07 23:25:27.478 ubuntu kernelmanager:89] Kernel started: bd732170-24fd-4262-a6b3-37d2a1362006
    [IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: u'comm_open'
    [IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: u'comm_open'
    [IPKernelApp] ERROR | Exception in message handler:
    Traceback (most recent call last):
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
        handler(stream, idents, msg)
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
        user_expressions, allow_stdin)
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/bash_kernel/kernel.py", line 146, in do_execute
        self.bashwrapper.run_command(code.rstrip(), timeout=None)
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/pexpect/replwrap.py", line 95, in run_command
        if self._expect_prompt(timeout=timeout) == 1:
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/bash_kernel/kernel.py", line 44, in _expect_prompt
        timeout=None)
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/pexpect/spawnbase.py", line 383, in expect_exact
        pattern_list = [prepare_pattern(p) for p in pattern_list]
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/pexpect/spawnbase.py", line 377, in prepare_pattern
        self._pattern_type_err(pattern)
      File "/opt/Anaconda2-4.3.0-Linux-x86_64/lib/python2.7/site-packages/pexpect/spawnbase.py", line 172, in _pattern_type_err
        for ast in self.allowed_string_types])
    TypeError: got <type 'str'> ('\r\n') as pattern, must be one of: <type 'unicode'>, pexpect.EOF, pexpect.TIMEOUT
    [I 2017-02-07 23:27:27.719 ubuntu handlers:179] Saving file at /Untitled.ipynb

Evaluation of a simple cell containing the `ls /` command hangs forever and never displays any output.

Here are the versions of packages involved::

    ubuntu@master001:~$ python2
    Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
    ...
    >>> import bash_kernel 
    >>> bash_kernel.__version__
    '0.5'
    >>> import pexpect
    >>> pexpect.__version__
    '4.2.1'

**Comment by takluyver** [comment]
Thanks, this was already fixed (#58), but just waiting for a new release.

**Comment by takluyver** [comment]
(Which I just did - should have made that clearer)

**Comment by riccardomurri** [comment]
Works great, thank you so much for the quick fix!
