### ISSUE TITLE
Error when typing `\`

### ISSUE THREAD

**Issue by kylebarron** [takluyver/bash_kernel#73]
Every time I type `\` for line continuation, the following error appears:
```
[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last):
File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell handler(stream, idents, msg) 
File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 434, in complete_request matches = self.do_complete(code, cursor_pos) 
File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/bash_kernel/kernel.py", line 201, in do_complete output = self.bashwrapper.run_command(cmd).rstrip() 
File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/pexpect/replwrap.py", line 100, in run_command
+ command)
ValueError: Continuation prompt found - input was incomplete: compgen -cdfa \
```

![image](https://user-images.githubusercontent.com/15164633/36518374-20b16226-1754-11e8-91de-38e67c3cd9ce.png)

**Comment by kdm9** [comment]
This was fixed in #133
