### ISSUE TITLE
scala run time error in jupyter

### ISSUE THREAD

**Issue by ebrahim100** [takluyver/bash_kernel#77]
I want to activate scala kernel on jupyter
It's run on windows 10

```
> PS C:\Users\ebrah\jupyter-scala> jupyter console --kernel scala --debug
[ZMQTerminalIPythonApp] No files in C:\Users\ebrah/.ipython\nbextensions
[ZMQTerminalIPythonApp] Searching ['C:\\Users\\ebrah\\jupyter-scala', 'C:\\Users\\ebrah\\.jupyter', 'E:\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in E:\Anaconda3\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\ebrah\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\ebrah\jupyter-scala
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in E:\Anaconda3\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\ebrah\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\ebrah\jupyter-scala
[ZMQTerminalIPythonApp] Connection File not found: C:\Users\ebrah\AppData\Roaming\jupyter\runtime\kernel-4084.json
[ZMQTerminalIPythonApp] Starting kernel: ['java', '-noverify', '-jar', 'C:\\Users\\ebrah\\AppData\\Roaming\\jupyter\\kernels\\scala\\launcher.jar', 'launch', '-r', 'sonatype:releases', '-r', 'sonatype:snapshots', '-i', 'ammonite', '-I', 'ammonite:org.jupyter-scala:ammonite-runtime_2.11.11:0.8.3-1', '-I', 'ammonite:org.jupyter-scala:scala-api_2.11.11:0.4.2', 'org.jupyter-scala:scala-cli_2.11.11:0.4.2', '--', '--id', 'scala', 'develop', '--name', 'Scala(develop)', '--quiet', '--connection-file', 'C:\\Users\\ebrah\\AppData\\Roaming\\jupyter\\runtime\\kernel-4084.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:49260
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:49257
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:49257
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:49258
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:49258
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:49259
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:49259
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:49261
[2KException in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
        at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
        at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
        at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at caseapp.App$class.apply(App.scala:46)
        at jupyter.scala.JupyterScalaApp.apply(JupyterScala.scala:13)
        at caseapp.AppOf.main(App.scala:121)
        at jupyter.scala.JupyterScala.main(JupyterScala.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at coursier.cli.qJ.a(Unknown Source)
        at coursier.cli.qI.j(Unknown Source)
        at coursier.cli.qO.a(Unknown Source)
        at d.g.a.c(Unknown Source)
        at b.b.d_(Unknown Source)
        at d.b.d.E.g(Unknown Source)
        at d.b.e.aU.g(Unknown Source)
        at a.c.a(Unknown Source)
        at coursier.cli.qI.b(Unknown Source)
        at coursier.cli.O.b(Unknown Source)
        at b.I.d_(Unknown Source)
        at d.E.h(Unknown Source)
        at a.aH.a(Unknown Source)
        at coursier.cli.Coursier.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at coursier.Bootstrap.main(Bootstrap.java:412)
Caused by: java.lang.NullPointerException
        at ammonite.runtime.Classpath$.classpath(Classpath.scala:31)
        at ammonite.interp.Interpreter.init(Interpreter.scala:93)
        at ammonite.interp.Interpreter.processModule(Interpreter.scala:409)
        at ammonite.interp.Interpreter$$anonfun$10.apply(Interpreter.scala:151)
        at ammonite.interp.Interpreter$$anonfun$10.apply(Interpreter.scala:148)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at ammonite.interp.Interpreter.<init>(Interpreter.scala:148)
        at jupyter.scala.Interp$$anon$3.<init>(Interp.scala:41)
        at jupyter.scala.Interp.<init>(Interp.scala:41)
        at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:98)
        at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:97)
        at jupyter.kernel.server.Server$.launch(Server.scala:80)
        at jupyter.kernel.server.Server$.apply(Server.scala:123)
        at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
        at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
        at scala.util.Try$.apply(Try.scala:192)
        at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:171)
        ... 36 more
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 323, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "E:\Anaconda3\lib\site-packages\jupyter_client\client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\jupyter_client\blocking\channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\Scripts\jupyter-console-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "E:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-117>", line 2, in initialize
  File "E:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\jupyter_console\app.py", line 141, in initialize
    self.init_shell()
  File "E:\Anaconda3\lib\site-packages\jupyter_console\app.py", line 114, in init_shell
    client=self.kernel_client,
  File "E:\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "E:\Anaconda3\lib\site-packages\jupyter_console\ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request``
```

**Comment by takluyver** [comment]
This is `bash_kernel`, not `scala_kernel` ;-)
