### ISSUE TITLE
pexpect.exceptions.TIMEOUT

### ISSUE THREAD

**Issue by elgalu** [takluyver/bash_kernel#80]
Below is the stack-trace, started to happen after some upgrades.

```
[D 2018-10-27 18:31:57.479 SingleUserLabApp connect:542] Connecting to: tcp://127.0.0.1:54813
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/bash_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/bash_kernel/kernel.py", line 81, in __init__
    self._start_bash()
  File "/opt/conda/lib/python3.6/site-packages/bash_kernel/kernel.py", line 104, in _start_bash
    line_output_callback=self.process_output)
  File "/opt/conda/lib/python3.6/site-packages/bash_kernel/kernel.py", line 33, in __init__
    prompt_change, extra_init_cmd=extra_init_cmd)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/opt/conda/lib/python3.6/site-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/opt/conda/lib/python3.6/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fba7552bc88>
command: /bin/bash
args: [b'/bin/bash', b'--rcfile', b'/opt/conda/lib/python3.6/site-packages/pexpect/bashrc.sh']
buffer (last 100 chars): ';10m@\x1b[30m\x1b[0;10mjupyter-lgallucci\x1b[30m\x1b[0;10m \x1b[32m/n/d/local\x1b[30m\x1b[0;10m (master)\x1b[30m\x1b[0;10m> \x1b[K'
before (last 100 chars): ';10m@\x1b[30m\x1b[0;10mjupyter-lgallucci\x1b[30m\x1b[0;10m \x1b[32m/n/d/local\x1b[30m\x1b[0;10m (master)\x1b[30m\x1b[0;10m> \x1b[K'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 2576
child_fd: 37
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\\$')
```

**Comment by elgalu** [comment]
Maybe is fixed with #69 ?

**Comment by schlichtanders** [comment]
same problems here

- bash_kernel 0.7.1
- jupyter 1.0.0
- python 3.5.2

**Comment by lexnederbragt** [comment]
Same problem here

* bash_kernel 0.7.2
```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 5.7.8
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.3
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3
```
* Python 3.6.10

```
$ pip install pexpect
Requirement already satisfied: pexpect in /anaconda3/lib/python3.6/site-packages (4.8.0)
Requirement already satisfied: ptyprocess>=0.5 in /anaconda3/lib/python3.6/site-packages (from pexpect) (0.6.0)
```

**Comment by leonexis** [comment]
I ran into this issue as well. It turns out that replwrap is expecting `$` as the prompt character, but I use powerline which doesn't use this convention. As a result, it continues waiting for input prompt that it will not see (because the assumption was incorrect). I could just disable powerline and go back to a default prompt that ends in `$`, but instead I modified `_start_bash` to use my own prompt instead (kernel.py around line 101):

```python
            # Using IREPLWrapper to get incremental output
            # self.bashwrapper = IREPLWrapper(child, u'\$', prompt_change,
            self.bashwrapper = IREPLWrapper(child, u'\ue0b0', prompt_change,
                                            extra_init_cmd="export PAGER=cat",
                                            line_output_callback=self.process_output)
```

Ideally this would be a configuration option or somehow run bash with an override prompt. I'm not sure how to do that, but hopefully this quick fix will help.

**Comment by kdm9** [comment]
In recent bash_kernel, we overwrite these settings with the expected values, so that the expectations of IREPLWrap aren't affected by user .bashrc settings (unless of course you manually source bashrc). Therefore I'm closing this as it should not happen, but please reopen if the problem persists or you notice further similar issues.
