### ISSUE TITLE
atom bash_kernel on windows not work

### ISSUE THREAD

**Issue by thomas10-10** [takluyver/bash_kernel#84]
Hello
On my atom editor with kernel jupyter bash_kernel on windows 10
i have this error 
Traceback (most recent call last): File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\bash_kernel__main__.py", line 3, in IPKernelApp.launch_instance(kernel_class=BashKernel) File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance app.initialize(argv) File "<C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error return method(app, args, **kwargs) File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize self.init_kernel() File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel user_ns=self.user_ns, File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\traitlets\config\configurable.py", line 412, in instance inst = cls(args, **kwargs) File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\bash_kernel\kernel.py", line 81, in init self._start_bash() File "C:\Users\toto\AppData\Local\Programs\Python\Python37\lib\site-packages\bash_kernel\kernel.py", line 95, in _start_bash child = pexpect.spawn("bash", ['--rcfile', bashrc], echo=False, AttributeError: module 'pexpect' has no attribute 'spawn'

Thanks
![capture](https://user-images.githubusercontent.com/36126914/53452700-5ae88e00-3a22-11e9-9448-bc9d7a5b739a.PNG)

**Comment by takluyver** [comment]
bash_kernel expects a POSIX environment. It might work in the Windows Subsystem for Linux; I haven't tried.
