### ISSUE TITLE
pexpect.spawn does not work under windows.

### ISSUE THREAD

**Issue by BoPeng** [takluyver/bash_kernel#96]
There are some bash implementations such as `git-bash` and `m2-bash` (through conda-forge) under windows. After installing `bash_kernel`, starting a Bash notebook lead to the following error message

```
Traceback (most recent call last):
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\bash_kernel\__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=BashKernel)
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\ipykernel\kernelapp.py", line 542, in initialize
    self.init_kernel()
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\bash_kernel\kernel.py", line 81, in __init__
    self._start_bash()
  File "C:\Users\bpeng1\AppData\Local\Continuum\anaconda3\envs\sos\lib\site-packages\bash_kernel\kernel.py", line 95, in _start_bash
    child = pexpect.spawn("bash", ['--rcfile', bashrc], echo=False,
AttributeError: module 'pexpect' has no attribute 'spawn'
```

which is a known problem for `pexpect` ([pexpect/pexepct#321](https://github.com/pexpect/pexpect/issues/321)). The sos kernel gets around this exact problem by [using `pexpect.popen_spawn`](https://github.com/vatlab/sos/blob/master/src/sos/utils.py#L1652)
but I am not sure if the solution applies to `bash_kernel`.

**Comment by BoPeng** [comment]
Ohmm, I also did the `child.echo = echo` hack, perhaps I was not far from getting `bash_kernel` work. 

Is https://github.com/Calysto/calysto_bash supposed to work under windows? If so, should we try to add it to `conda_forge` first?

**Comment by takluyver** [comment]
I don't intend to support Windows. And I'd rather it just didn't work on Windows at all than sort-of worked.

It maybe works in WSL, but in that case I imagine you'd need a Linux package anyway.
